import { RangeValue } from "rc-picker/lib/interface";
import { Dayjs } from "dayjs";
import { Program } from "../models/programAddModel";


//
//CREATE_CLASS_DATA_ACTION_TYPE
export const FETCH_CREATE_CLASS_DATA_REQUEST =
  "FETCH_CREATE_CLASS_DATA_REQUEST";
export const FETCH_CREATE_CLASS_DATA_SUCCESS =
  "FETCH_CREATE_CLASS_DATA_SUCCESS";
export const FETCH_CREATE_CLASS_DATA_FAILURE =
  "FETCH_CREATE_CLASS_DATA_FAILURE";
//
// CREATE_CLASS_ACTION_TYPE
export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
//
// PROGRAM_ACTION_TYPE
export const FETCH_PROGRAMS_REQUEST = "FETCH_PROGRAMS_REQUEST";
export const FETCH_PROGRAMS_SUCCESS = "FETCH_PROGRAMS_SUCCESS";
export const FETCH_PROGRAMS_ERROR = "FETCH_PROGRAMS_ERROR";
//
//PROGRAM_TOPIC_ACTION_TYPE
export const FETCH_PROGRAM_CONTENT_REQUEST = "FETCH_PROGRAM_CONTENT_REQUEST";
export const FETCH_PROGRAM_CONTENT_SUCCESS = "FETCH_PROGRAM_CONTENT_SUCCESS";
export const FETCH_PROGRAM_CONTENT_ERROR = "FETCH_PROGRAM_CONTENT_ERROR";
//TRAINEE_ACTION_TYPE
export const FETCH_TRAINEES_TOTAL_REQUEST = "FETCH_TRAINEES_TOTAL_REQUEST";
export const FETCH_TRAINEES_REQUEST = "FETCHT_TRAINEES_REQUEST";
export const FETCH_TRAINEES_SUCCESS = "FETCH_TRAINEES_SUCCESS";
export const FETCH_TRAINEES_ERROR = "FETCH_TRAINEES_ERROR";
export const FETCH_TRAINEES_ATTENDANCE = "FETCH_TRAINEES_ATTENDANCE";
//SCHEDULE_ACTION_TYPE
export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_ERROR = "FETCH_SCHEDULE_ERROR";
//ATTENDANCE_ACTION_TYPE
export const FETCH_ATTENDANCE_REQUEST = "FETCH_ATTENDANCE_REQUEST";
export const FETCH_ATTENDANCE_SUCCESS = "FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_ERROR = "FETCH_ATTENDANCE_ERROR";


//
export interface GeneralSchedule {
  id: number;
  time: RangeValue<Dayjs>;
  dayOfWeek: string | null;
}
